name: macOS

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "trunk" ]

env:
  MARGS: "-j2"
  
jobs:

  build:
    strategy:
      matrix:
        os: [ "macos-latest" ]

    runs-on: ${{ matrix.os }}
    env:
      NOTEST_CFLAGS: ${{ matrix.notest-cflags }}
    name: ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v3
    - name: buildconf
      run: ./buildconf
    - name: configure
      run: ./configure
    - name: make
      run: make $MARGS
    - name: make check
      run: make check
